name: CI
on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Setup Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build
      #   run: npm run build

      # - name: Test
      #   run: npm run test

      - name: Trigger Release
        if: github.ref == 'refs/heads/main'
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          event_type: semantic-release

      # - name: Trigger Deployment to Staging
      #   if: github.ref == 'refs/heads/develop'
      #   uses: mvasigh/dispatch-action@main
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     event_type: deploy-to-staging
