name: Release
on:
  repository_dispatch:
    types: [semantic-release]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        name: Semantic Release
        run: npx semantic-release

      - name: Trigger deployment to production
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          event_type: deploy-to-prod
